name: Weekly Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 * * 3'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.18
  CONSUL_VERSION: 1.12.1
  TERRAFORM_VERSION: 1.2.2
  VAULT_VERSION: 1.10.3

jobs:
  compatability:
    name: Compatability Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run compatability tests
        run: |
          make test-compat

  vault-integration:
    name: Vault Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Vault
        uses: ./.github/actions/setup-vault
        with:
          version: ${{ env.VAULT_VERSION }}

      - name: Run Vault integration tests
        run: |
          make test-vault-integration

  benchmarks:
    name: Benchmarks Tests
    runs-on: ubuntu-latest
    timeout-minutes: 150
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Consul
        uses: ./.github/actions/setup-consul
        with:
          version: ${{ env.CONSUL_VERSION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Copy Terraform to test workdir
        run: |
          cp /usr/local/bin/terraform ./e2e/benchmarks/

      - name: Run benchmarks tests
        run: |
          set -euo pipefail
          mkdir -p .build
          make test-benchmarks | tee .build/benchmarks-output.json

      - name: Parse benchmarks output
        run: |
          set -euo pipefail
          grep 'ns/op' .build/benchmarks-output.json | \
            jq -r .Output \
            | sed 's/\t/ /g' \
            | tr -s ' \n' \
            | sed 's/ /,/g' \
            | sort -r \
            | tee .build/benchmarks-results-${GITHUB_SHA}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}.csv

      - uses: actions/upload-artifact@v3
        with:
          name: benchmarks-results
          path: .build/benchmarks-results*.csv

  slack-notification:
    name: Slack Notification
    if: |
      failure()
    needs:
      - compatability
      - vault-integration
      - benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
